spring:
  datasource:
    url: jdbc:h2:mem:users
    username: nikhil
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      use-new-id-generator-mappings: false

server:
  port: 8080